remote_theme: b2a3e8/jekyll-theme-console
title: Isaac's Website
description: >- # this means to ignore newlines until "baseurl:"
  A blog showcasing a different cactus every day.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cactusoftheday.github.io" # the base hostname & protocol for your site
github_username: cactusoftheday

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - publications.md
  - gunpla.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

footer: 'Add me on <a href="https://www.linkedin.com/in/isaac-huang-0b3027246/">LinkedIn</a>'

google_analytics: UA-NNNNNNNN-N

defaults:
- scope:
    path: "" # an empty string here means all files in the project
  values:
    layout: "default"